---
create_value_proposition_canvas_task:
  description: 'Create a Value Proposition Canvas  based
    on the provided target audience: {TARGET_AUDIENCE}
    and product/service description: {PRODUCT_DESCRIPTION} '
  expected_output: A 1 line Value Proposition Canvas is to be presented


  async_execution: false
  agent: value_proposition_canvas_creator
  output_file: report_canvas.md

analyze_4ps_task:
  description: 'You are a marketing analyst tasked with applying the 4Ps of Marketing framework to help understand a target audience and how a product/service aligns with their needs. You will be provided with information about the target audience and the product/service, and you should use this information to answer a series of questions about each of the 4Ps.

First, carefully read and analyze the following information about the target audience from the input:

 {TARGET_AUDIENCE} 
 and
 {PRODUCT_DESCRIPTION}
Using the provided information, answer in 1 line '

  expected_output:
    Ensure 1 line output for 4p analysis.

  async_execution: false
  agent: marketing_analyst
  output_file: report_4p.md


conduct_swot_analysis_task:
  description: 'You are tasked with conducting a SWOT analysis for a target audience.  Follow these instructions carefully to complete the task.

After analysing the specific target audience description from the input

 {TARGET_AUDIENCE} 
 follow these steps to conduct the SWOT analysis: Carefully read and analyze the target audience description..'
  expected_output: Present your completed SWOT analysis in 1 line format

  async_execution: false
  agent: swot_analyzer
  output_file: report_swot.md

map_buyers_journey_task:
  description: 'You are tasked with mapping out the Buyers Journey for a specific target audience and product description . 

First, review the following information:
{TARGET_AUDIENCE}
{PRODUCT_DESCRIPTION}
   
For each Stage, provide at least one key insight that can be used in a lead generation strategy.'

  expected_output: A concise 1 line analysis of the Buyers Journey stages with key insights for lead generation strategies. Use the information given to make informed assumptions and provide actionable insights.

  async_execution: false
  agent: buyers_journey_mapper
  output_file: report_buyers.md

combine_task:
  description: > 
    'Combine the outputs of the tasks create_value_proposition_canvas_task, analyze_4ps_task, conduct_swot_analysis_task, and map_buyers_journey_task into a single structured  format.'
  expected_output: >
    A Single 1 line output report that consolidates the complete outputs of all tasks in the below format:
    <Task_Details>
    [Include Agent_Name, Task_Description, Task_Output]
    </Task_Details>
  async_execution: false
  agent: output_formatter
  inputs:
    value_canvas: "{{create_value_proposition_canvas_task.output}}"
    4p_task: "{{analyze_4ps_task.output}}"
    swot_analysis: "{{conduct_swot_analysis_task.output}}"
    buyers_journey: "{{map_buyers_journey_task.output}}"
  context: [create_value_proposition_canvas_task, analyze_4ps_task, conduct_swot_analysis_task, map_buyers_journey_task]
  output_file: reports_combine.md
  verbose: true




